apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_EXAMPLE: ENC[AES256_GCM,data:CVxK26+/SDrKWqy4sm8+f3wXfz2rfG6HpMgPitvjmyTxEXH3PO8YPGyUgnyNYoSuKpvWzUChEXEitGjg5escInDccwBU/NEddDc6IGPbeqz5HJsJNNO902mrKzYyzg==,iv:G8htopNqjasCEeTWp5uWOkikfcaSMhjzjQ/Hc+Z8QQk=,tag:kOEEOWaucs3gvZ5YiDsWOQ==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:9PGvvogvLkFd4H7im/pC,iv:/mWIffsJR+Zthr9kesc6NloTobDmZKpOrXez/CVdVOI=,tag:KnY+RA5A5T41nDH2nJWKmg==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:qWw6Oh+la0yPo5c4Iw==,iv:tckxVxB8bSztiOzNztx/3cewuRx8zkTIb3OmwkN81kQ=,tag:Y+2erd7WNuoF7/iPDu2GXw==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:LY5ZMxgl8IwWyn2Km3bU105+adFyqyF4/azj3nv0F2i/pHbP,iv:8J94wuoVHCxiXJw5OWobm95MArddMjmxvXesX+oOSik=,tag:4AF8O2mQr7pElo95+JRsFg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17hz3ylunaz3yuxxdchyp5gmprxekkll4zwgfwq0e4wyl0vefg3lqr6lwnc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoT3hubTErWmdPUXRSazRB
            Q0pFQWNUNkJCY0x6TG9GY0dzSXJQeUZHbGtJCm1mZEJOcnZmaGs2OExId3p2bXNZ
            a3NwaTE4UGJtZ2I3MjJRbzYybWcxUk0KLS0tIGpMYTBHbURCb3dwN25OUzBMS2hQ
            bUFwaHp6OEhYRFNIRWJwWDROZ3MzZk0K3De4fvQNnIM2CkjFC7wG9aBlcbBT6mGm
            +t7De0ae59eozfWXtp0IBs15O6OavrrefNCtYlO8nqK3eIMDl0AxGw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-26T15:54:33Z"
    mac: ENC[AES256_GCM,data:wL2V549LOD7jC+zIXJy040FKB7hNJMW76RIbfe+/DFDqT1dbrKkZtnD5KDeN/aIe36G1lQtEeQ7PAgaH49RzWH95T8uKqcawacgjqZHrReGicI1vH2jWRJl02Rs4dS93A5IC0blpYobWJG8FdEyfSGMkHINvAXdQu7XRCfw99pw=,iv:d6H0FwUJwByeSdjauwk087L+8h1ijNNMyhFWWr0l+n4=,tag:GTQduGsU5NZ+KblXKY02mg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
