apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:04qRhaW4xXznje5qOK5LYNmfUKo7rJQftcWfGGwnF+EcYjolbREfBA==,iv:IBkPE4GWhiAjSPth4xIZ1KEmk0mfySzlDVhT8jJIHxI=,tag:IubkPKTGVd89WfhUNIqf1A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17hz3ylunaz3yuxxdchyp5gmprxekkll4zwgfwq0e4wyl0vefg3lqr6lwnc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaMHhjdzdXeGt5OG1FdXBU
            bkgwcnR0SkxlejdocnJMYjhqMmhwV0Z3cEdzCnhPZkhCMkJxMi9CUUJYZ1kvY2tt
            YlNGZm9WZ2syamo0RFU1dHlEUi8wdmMKLS0tIFI0QkdpVnZBTEhOVjJBaWo2aDZy
            MmFxdHMvSmFsY25XeEtTdjJlNHdndVUKxOR8Y5eljjQV6D6GaEC1AWQ4DTl6Saw4
            KjKnjlYT/7rJqLP4DZomLNFBT7G0rBA2MNca5Qn8LmUyF4Ugy0zAXg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-26T15:37:12Z"
    mac: ENC[AES256_GCM,data:bJ60z0yiA41fzS7OJ/skV0WuDM5eX85/0LsHknf7/t596A7TO2el7ZwoFHGFZisjS49BOlxmyrVhMRK0azLoi0rp/1kDx5I+Lu8ju5nJ04MLvGZa6FajYLQsbPH/FAovOGMP2maoVlHAssT0zhmFqC5q12QEri4r4e1rP9sFw28=,iv:J5w035iM8AF0DU2qZTutTBLZCJtjlnSK8iIDqbh/vZE=,tag:vsG5CrSaYIDfB5sh1+94BQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
